# Generated by Django 5.0.1 on 2025-02-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_website', '0003_alter_ai_llm_image_alter_certificate_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ai_llm',
            old_name='link_to_ai_llm',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='link_to_certificate',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='diploma',
            old_name='link_to_diploma',
            new_name='link',
        ),
    ]
